version: 2

workflows:
  version: 2
  tests:
    jobs:
      - install
      - test:
        name: Test
        requires:
          - install

jobs:
  install:
    docker:
      - imageL circleci/node:8

    steps:
      - checkout
      - run:
        name: Install dependencies
        command: npm install

  test:
    - run:
        name: Lint code
        command: npm run lint
    - run:
        name: Run tests
        command: npm test
    - run:
        name: Semantic release
        command: npm run semantic-release || true
