version: 2

workflows:
  version: 2
  main:
    jobs:
      - lint
      - test-v4
      - test-v5
      - test-v6

jobs:
  lint:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint code
          command: npm run lint
  test-v4:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint code
          command: npm run test:v4

  test-v5:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint code
          command: npm run test

  test-v6:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint code
          command: npm run test:v6
